### ISSUE TITLE
Glossar

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#2]
Wir benötigen separate Felder für Name und Vorname, damit wir die Glossarliste alphabetisch sortieren können, auch wenn die Namen zusammengeschrieben mit Vorname am Anfang stehen. Ich habe schon mal Personen eingetragen nach Ordnung "Nachname, Vorname". Das jetzige Feld kann dann für den Nachnamen sein. Wenn das Vornamenfeld da ist, trage ich das im Nachgang dann um.

**Comment by stephan-harmanus** [comment]
In der Glossarübersicht nur die Namen. "Textvoransicht" und "Weiterlesen" kann weg. Dann können die Namen schön eng untereinanderlaufen. Das werden nämlich richtig viele!

**Comment by Andreas-Schoenefeldt** [comment]
Sortierung nach Vorname und Nachname der Ansicht.

**Comment by Andreas-Schoenefeldt** [comment]
Wird noch mit dem Bacharchiev geklärt.
