### ISSUE TITLE
Bug Editor

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#26]
![bildschirmfoto 2016-11-16 um 06 26 21](https://cloud.githubusercontent.com/assets/23217462/20335794/e23e144e-abc5-11e6-9246-c3408549d89f.png)
1. Wenn ich bei "unsicheres Datum" ein Häkchen setze, erscheint der Eintrag nicht mehr in der Timeline.
2. Wenn ich Navigationspunkt auswähle z.B. ""Geistliche Kantaten, BWV 1-200 (13)"", wird der Navigationspunkt mit doppelten Anführungszeichen ausgegeben. Dann erscheint er nicht mehr korrekt auf der Website. Wenn ich einmal Anührungszeichen wegnehme, geht es.

**Comment by Andreas-Schoenefeldt** [comment]
Haben wir gelößt, indem wir das Backend auf Auswahlbox anstelle von Tag display umgestellt haben
