### ISSUE TITLE
Timeline: Schwebende Labels für Beschriftung der Zeitphasen

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#30]
Da die Beschriftung der Zeitphasen unten durch die nächstfolgende Zeitphase verdeckt wird, sollen diese wie in den Kategorien als schwebende Labels sich anordnen, so dass sich die Labels aneinandervorbeischieben, wenn sie sich überdecken würden.

**Comment by Andreas-Schoenefeldt** [comment]
Das sie sich wirklich übereinanderschieben ist nicht so leicht möglich - sie müssten dann mit in die Berechnung der timeline einträge hinein, wo sie im Moment ignoriert werden

Als quikfix bau ich mal ein, das zumindest beim mouseover alles angezeigt wird.

**Comment by stephan-harmanus** [comment]
ok, gute Idee

**Comment by Andreas-Schoenefeldt** [comment]
Ok, Ich habe es jetzt angepasst - ich denke mal viel anders können wir das heute nicht machen.

**Comment by stephan-harmanus** [comment]
ist doch gut gelöst
