### ISSUE TITLE
Glossar Eintrag: Person - Sortierung

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#31]
- Dokumente: chrologogisch und alphabetische Ordnung per Radiobutton

**Comment by stephan-harmanus** [comment]
Personen: Auswahlliste chronologisch und nach: Familie, Freunde, Feinde, Kollegen, Mäzene, Schüler, Vorbilder, Vorgesetzte

**Comment by Andreas-Schoenefeldt** [comment]
Hi Stephan, 

kannst du mir dazu bitte einen Layoutvorschlag machen?

1000 Dank

**Comment by Andreas-Schoenefeldt** [comment]
Person als eigenen Typ anlegen?

**Comment by Andreas-Schoenefeldt** [comment]
Für die Datenmigration:
1. Löschen
1. Neue Person als Person Eintrag anlegen mit dem selben Titel 

so bleibt hoffentlich der URL alias identisch und die verlinkungen funktionieren dann noch

**Comment by stephan-harmanus** [comment]
![bildschirmfoto 2016-12-05 um 11 59 07](https://cloud.githubusercontent.com/assets/23217462/20882667/51a9a2aa-bae2-11e6-9a44-2bcfaadb7d8e.png)

**Comment by stephan-harmanus** [comment]
![bildschirmfoto 2016-12-05 um 12 00 56](https://cloud.githubusercontent.com/assets/23217462/20882705/81f971e2-bae2-11e6-9b87-9057ea4f5edf.png)

**Comment by Andreas-Schoenefeldt** [comment]
Hi Stephan,

du kannst es jetzt migrieren. 

1. Alte Seite öffnen
2. in einem 2. Tab einen Neuen Inhalt vom Typ Person anlegen
3. den alten Inhalt löschen
4. den neuen Inhalt Speichern und anlegen (um zu verhindern, das der url alias schon belegt ist)

Liebe Grüße
Andreas

**Comment by Andreas-Schoenefeldt** [comment]
Ok, ich muss für heute schluss machen - der Filter ist grundsätzlich eingebaut
