### ISSUE TITLE
Website: Navigationshierarchie für Werke und Orte erstellen

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#32]
1 Vokalwerke – BWV 1–524
	• 1.1 Kantaten, BWV 1–224
	• 1.2 Motetten, BWV 225–231
	• 1.3 Messen, BWV 232–236
	• 1.4 Einzelne Messsätze, BWV 237–242
	• 1.5 Magnificat, Passionen, Oratorien, BWV 243–249
	• 1.6 Vierstimmige Choralsätze, BWV 250–438
	• 1.7 Lieder und Arien, BWV 439–524
2 Orgelwerke – BWV 525–771
	• 2.1 Nicht choralgebundene Werke, BWV 525–598
	• 2.2 Choralsätze, BWV 599–771
3 Klavierwerke – BWV 772–994
	• 3.1 Zwei- und dreistimmige Werke, BWV 772–805
	• 3.2 Suiten, BWV 806–845
	• 3.3 Präludien und Fugen, BWV 846–962
	• 3.4 Sonaten, Konzerte, Variationen, BWV 963–994
4 Kammermusik – BWV 995–1040
	• 4.1 Werke für Laute, BWV 995–1000, 1006a
	• 4.2 Werke für ein Soloinstrument, BWV 1001–1013
	• 4.3 Sonaten mit Cembalo oder Continuo, BWV 1014–1040
5 Orchesterwerke – BWV 1041–1071
	• 5.1 Konzerte, BWV 1041–1065
	• 5.2 Suiten, BWV 1066–1071
6 Kontrapunktische Werke – BWV 1072–1080
7 Weitere Werke
	• 7.1 Später eingereihte Kompositionen, BWV 1081–1128
	• 7.2 Anhang I – Fragmente und verschollene Werke, BWV Anh. 1–23
	• 7.3 Anhang II – Zweifelhafte Werke, BWV Anh. 24–155
	• 7.4 Anhang III – Fälschlich zugeschriebene Werke, BWV Anh. 156–189
	• 7.5 Spätere Ergänzungen zum Anhang, BWV Anh. 190–213

**Comment by stephan-harmanus** [comment]
Orte:
1. Hierarchie-Ebene: Orte (chronologisch)
2. Hierarchie-Ebene: Gebäude (alphabetisch geordnet)

**Comment by Andreas-Schoenefeldt** [comment]
Das alle ausgeklappt sind, muss noch extra angeklickt werden - bei Menü bearbeiten -> Link bearbeiten -> "als ausgeklappt angzeigen"

- Darstellungsanpassungen - lenke Spalte breiter, fancy scroll menü mit toller klick funktion
