### ISSUE TITLE
Design Startseite anpassen

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#33]
![bildschirmfoto 2016-12-07 um 15 49 17](https://cloud.githubusercontent.com/assets/23217462/20972318/ccba5184-bc94-11e6-801c-8728787695fa.png)
![dlr](https://cloud.githubusercontent.com/assets/23217462/20972342/da27e78c-bc94-11e6-8a7c-242d216dcdd1.jpg)
Logo DLR mit einbinden. Wichtig für Präsentation, weil großer Partner!

**Comment by Andreas-Schoenefeldt** [comment]
Orte, Personen, etc - sind die Subnavigation 
Formum - will be probably be dissabled

**Comment by Andreas-Schoenefeldt** [comment]
Mediathek - Liste aller EInträge mit Audiobeispielen.

**Comment by Andreas-Schoenefeldt** [comment]
Hi Stephan, ich denke mit der Suche müssen wir noch was machen, die ist im moment vom aussehen her etwas dodgy - eventuell ist dort wo Suche steht der input ud suche ist nur der default? Eventuell kann man noch eine linie drunter zeichnen?

**Comment by stephan-harmanus** [comment]
Hab ich nicht verstanden. Lass uns da mal skypen
