### ISSUE TITLE
Website: Fehlerdarstellung Bilder, zu groß

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#34]
![bildschirmfoto 2016-11-29 um 08 26 05](https://cloud.githubusercontent.com/assets/23217462/20700463/c9acff92-b60d-11e6-9c60-3c01a21dffc6.png)
Bitte einstellen, dass Bilder beim Upload auf passende Größe runtergerechnet werden und Fancybox ansteller der Lupenfunktion einrichten.

**Comment by Andreas-Schoenefeldt** [comment]
Hi Stephan, das sollte jetzt passen. Ich habe auch den Image Zoom angepasst.
