### ISSUE TITLE
Timeline: Youtube Video Sound spiel noch weiter, wenn das Fenster geschlossen wird

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [KplusH/jsbach-timeline#37]
~ Januar 1708
„Aus der Tiefen, rufe ich, Herr, zu dir“ BWV 131
Hier habe ich eine Youtube Video eingebunden. Das muß noch in der Timeline erscheinen.

Soll unter den Audioeinträgen dargestellt werden.

**Comment by Andreas-Schoenefeldt** [comment]
Hi Stephan,

der ausgewählte Link muss immer der embed link sein:

<img width="671" alt="screen shot 2016-12-05 at 15 09 06" src="https://cloud.githubusercontent.com/assets/1157580/20889991/1a676fdc-bafd-11e6-98a6-095c6a3bae65.png">

Liebe Grüße
Andreas

**Comment by Andreas-Schoenefeldt** [comment]
Done :)

**Comment by stephan-harmanus** [comment]
Das Video bzw. der Sound stoppt nicht, wenn das Fenster geschlossen wird.

**Comment by Andreas-Schoenefeldt** [comment]
Ok, wenn es so wichtig ist 😏

**Comment by stephan-harmanus** [comment]
Ja, sonst läufts per der Präse weiter und Maul weiß nicht wie abstellen

**Comment by Andreas-Schoenefeldt** [comment]
Der Player stopt jetzt, wenn das Modal geschlossen wird.
