### ISSUE TITLE
Timeline: Bewertungstufen

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#40]
Es gibt Verwirrung bei den Bedeutungsstufen der Timeline, da wir mit Stufe "Keine" nun 4 Stufen haben. Daher folgenden Aufbau. Bitte Stufe "keine" löschen und diese Größenformattierung auf Stufe "wichtig" anwenden. Stufe "wichtig" wird dann standardmäßig angeboten.

Dann bin ich für eine Umbenennung der Stufen in: neutral, hervorheben, stark hervorheben.

**Comment by Andreas-Schoenefeldt** [comment]
Done 😸
