### ISSUE TITLE
Website: Im Editor zusätzliche Option "Text bereinigen" bereitstellen

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#41]

**Comment by Andreas-Schoenefeldt** [comment]
Das ist dieser hier:  <img width="55" alt="screen shot 2016-12-19 at 16 32 13" src="https://cloud.githubusercontent.com/assets/1157580/21318273/ca411352-c608-11e6-9a27-6cefa6ccf119.png">
