### ISSUE TITLE
Website: Debugging

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#43]
![bildschirmfoto 2016-12-09 um 08 03 31](https://cloud.githubusercontent.com/assets/23217462/21040672/a4691b2c-bde6-11e6-9bc7-0394392dd909.png)
![bildschirmfoto 2016-12-09 um 08 04 36](https://cloud.githubusercontent.com/assets/23217462/21040671/a468d89c-bde6-11e6-821b-2a99f16b16fe.png)

Navigation wrid nich ausgegeen, obwohl im Editor eingestellt

**Comment by stephan-harmanus** [comment]
![bildschirmfoto 2016-12-09 um 08 09 42](https://cloud.githubusercontent.com/assets/23217462/21040718/e0b9b564-bde6-11e6-8ffc-3c4811977d86.png)

Subnavigation bei Werke ist nicht mehr da

**Comment by Andreas-Schoenefeldt** [comment]
Wenn die Navigation links fehlt, hängt es am url pfad des contents - man kann schauen, ob der alias (Rechts in der Seite) automatisch generiert wird.

<img width="605" alt="screen shot 2016-12-09 at 10 11 44" src="https://cloud.githubusercontent.com/assets/1157580/21043635/1b0e59ac-bdf8-11e6-8830-05c5ee10fd3a.png">

**Comment by Andreas-Schoenefeldt** [comment]
I think the module kind of went astray...
