### ISSUE TITLE
Homebutton für timeline

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#44]
![bildschirmfoto 2016-12-09 um 08 26 46](https://cloud.githubusercontent.com/assets/23217462/21041230/f4e16e1c-bde9-11e6-8437-f1c22edc8692.png)

Bitte Homebutton einfügen. SVG-Grafik habe ich per Mail zugeschickt.

**Comment by Andreas-Schoenefeldt** [comment]
Hi Stephan, die ist jetzt mit drin :)

**Comment by stephan-harmanus** [comment]
ok, noch deutliche  Schatten drumrum, sonst wirkt´ so verloren

**Comment by Andreas-Schoenefeldt** [comment]
Done :)
