### ISSUE TITLE
Timelineeinträge bei Zeitgeschehen oben abgeschnitten

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#46]
![bildschirmfoto 2016-12-09 um 12 37 09](https://cloud.githubusercontent.com/assets/23217462/21047828/60b3b100-be0c-11e6-9000-4d730b3b63af.png)

**Comment by Andreas-Schoenefeldt** [comment]
Das ist, weil du ncoh eingeloggt bist... So solltet ihr nicht präsentieren.

**Comment by Andreas-Schoenefeldt** [comment]
Ich werd da was einbauen, das man die navbar im eingeloggten Modus runter rutscht, ist aber imho nicht so wichtig.

**Comment by stephan-harmanus** [comment]
bin auf Safari nciht eingeloggt. da wird´ auch abgeschnitten!
