### ISSUE TITLE
Beitrag direkt aus der timeline bearbeiten können

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#47]
![bildschirmfoto 2016-12-16 um 21 48 59](https://cloud.githubusercontent.com/assets/23217462/21278098/8f49b690-c3d9-11e6-8c05-e08656fecc55.png)

**Comment by stephan-harmanus** [comment]
Ich denke, direkte Verlinkung zum Beitrag im Backend in einem neuen Tab, also kein Editorfenster.

**Comment by Andreas-Schoenefeldt** [comment]
Hi Stephan, der Link ist jetzt verfügbar.

Liebe Grüße
Andreas

**Comment by stephan-harmanus** [comment]
ok, danke!

Liebe Grüße
Stephan

__________________________________________

KplusH
Agentur für Kommunikation und Design
Inhaber Stephan Harmanus
Kyffhäuserstr. 23
D-10781 Berlin
telefon:  +49 30 23 63 25 06
mobil:    0178- 25 83 606
email: s.harmanus@k-plus-h.de <mailto:s.harmanus@k-plus-h.de>
web: www.k-plus-h.de <http://k-plus-h.de/>
