### ISSUE TITLE
Website: Audiobeispiel Fehlermeldung bei Glossareintrag

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#48]
![bildschirmfoto 2016-12-09 um 14 29 07](https://cloud.githubusercontent.com/assets/23217462/21052208/0eba1b56-be24-11e6-92b2-4f1f7c7ac8d7.png)

Legt man einen Glossareintrag an, bekommt mann eine Felermeldung, wenn man ein Soundbeispiel einbinden möchte.

**Comment by Andreas-Schoenefeldt** [comment]
Ah, da ist kluger Weise nur .txt erlaubt ;)

**Comment by stephan-harmanus** [comment]
![bildschirmfoto 2016-12-19 um 13 38 25](https://cloud.githubusercontent.com/assets/23217462/21313161/773bf9b4-c5f0-11e6-9cb9-419804b0129c.png)
Wenn man in einem Glossareintrag eine Audio-Datei hochläd bekommt man folgende falsche Fehlermeldung und es lässt sich kein Mp3-File hochladen: "Die angegebene Datei Track 02.mp3 konnte nicht hochgeladen werden. Nur Dateien mit folgenden Erweiterungen sind zulässig: txt."

**Comment by Andreas-Schoenefeldt** [comment]
Done :)
