### ISSUE TITLE
Cluster Event Possibility - Allows to group Timeline Events above a certain Zoom Level

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [KplusH/jsbach-timeline#49]
Porbably a new content type, which is only displayed from a certain zoom level on.

- Beschreibung des Events 
- start_date
- end_date
- title

Beim Klick auf den Cluster Möglichkeit den Bereich anzuzeigen

**Comment by Andreas-Schoenefeldt** [comment]
Das Handling der anderen Bereiche - sobald die events oben anstoßen wandeln wir alle unter einer bestimmten Wichtigkeit in Punkte um, die normal einsortiert werden.

**Comment by Andreas-Schoenefeldt** [comment]
Cluster sollen ein Icon vorne haben.

**Comment by Andreas-Schoenefeldt** [comment]
@stephan-harmanus - können wir so einen cluster mal in aktion testen, um das sehen zu können?

**Comment by stephan-harmanus** [comment]
Ich warte gerade auf die Zuarbeit von Manuel.Kommt demnächst, dann können wir einen Cluster anlegen und testen

**Comment by stephan-harmanus** [comment]
Kannst Du bei den Clusterfldern noch dafür sorgen, dass Textinformationen noch in der Timeline angezeigt werden. Es gibt im Redaktionssystem ein Feld "Body". Dort habe ich Text reinkopiert. Wird aber nicht in der Timeline ausgegeben.

**Comment by Andreas-Schoenefeldt** [comment]
done :)
