### ISSUE TITLE
Video spielt nicht ab

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#54]
19. April 1707 ?, „Nach dir, Herr, verlanget mich“ BWV 150.

**Comment by stephan-harmanus** [comment]
25. Dezember 1725, „Unser Mund sei voll Lachens“ BWV 110

**Comment by Andreas-Schoenefeldt** [comment]
Problem was, that not the embed link was used

<img width="604" alt="screen shot 2017-09-12 at 11 27 28" src="https://user-images.githubusercontent.com/1157580/30318440-669f13fe-97ad-11e7-94c8-c37d570a77f5.png">
