### ISSUE TITLE
Allow to link modals

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [KplusH/jsbach-timeline#55]
durch das anfügen von ```#in-timeline``` an einen link, soll das entsprechende Modal geöffnet werden.

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Stephan,

also wenn du zb http://jsbach.de/kalendarium#bt-1316 aufrufst, kannst du es im ersten link prüfen. Wichtig ist wie gesagt, das dem Link ```#in-timeline``` angehängt wird, sonst kann ich es nicht rausfinden.

Liebe Grüße
Andreas

**Comment by stephan-harmanus** [comment]
ok, bin gespannt

**Comment by Andreas-Schoenefeldt** [comment]
Eventuell musst du einmal den cache im browser löschen.
