### ISSUE TITLE
Detailansicht der Timeline

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [KplusH/jsbach-timeline#6]
![bildschirmfoto 2016-10-27 um 11 36 20](https://cloud.githubusercontent.com/assets/1157580/20182589/88e713c6-a762-11e6-9360-84f42a3c12e4.png)

**Comment by stephan-harmanus** [comment]
Das jetzt angelegte Textfeld für die Musikbespiele ist nicht lang genug. Text wird also abgeschnitten.

**Comment by stephan-harmanus** [comment]
Musikfiles habe ich alle wieder eingefügt

**Comment by stephan-harmanus** [comment]
![bildschirmfoto 2016-11-13 um 22 41 05](https://cloud.githubusercontent.com/assets/23217462/20249097/62e68408-a9f2-11e6-9890-ca0dd737b91b.png)
Bld wird abgeschnitten und Bildunterschrift sollte unter das Bild

**Comment by stephan-harmanus** [comment]
~ Januar 1708
„Aus der Tiefen, rufe ich, Herr, zu dir“ BWV 131
Hier habe ich eine Youtube Video eingebunden. Das muß noch in der Timeline erscheinen.

**Comment by stephan-harmanus** [comment]
![bildschirmfoto 2016-12-06 um 20 32 05](https://cloud.githubusercontent.com/assets/23217462/20940465/2b52ec9e-bbf3-11e6-9c64-a07a49bb133f.png)
Kannst Du durch einen &nbsp; dafür sorgen, dass zwischen Linkicon und Wort kein Zeilenumbruch stattfinden kann.

**Comment by Andreas-Schoenefeldt** [comment]
Hey Stephan, kurz vor Schluss den Scope zu ändern geht normalerweise nicht durch 😏

**Comment by stephan-harmanus** [comment]
oke-oke

**Comment by Andreas-Schoenefeldt** [comment]
Ok, die Sachen sind drin.
