### ISSUE TITLE
Startseite anpassen

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#62]
![bildschirmfoto 2017-11-06 um 09 44 52](https://user-images.githubusercontent.com/1157580/32440999-d6a4713a-c2f5-11e7-8d24-3342183e964a.png)

Startseite nach Screenshot anpassen

**Comment by stephan-harmanus** [comment]
Ausgegraute Links sind damit nicht aktiv

**Comment by Andreas-Schoenefeldt** [comment]
Möglich machen, das die Navigation im Eingeloggten Zustand funktioniert?

**Comment by stephan-harmanus** [comment]
Ja, das wäre fein

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Stephan, das ist jetzt geändert. Wenn du Menüpunkte bearbeitestm kannst du unter EIGENSCHAFTEN an oder abstellen, ob sie grau angezeigt werden und für nicht angemeldtete Benutzer funktionieren.

<img width="557" alt="screen shot 2017-11-07 at 01 46 17" src="https://user-images.githubusercontent.com/1157580/32471425-7dc9f568-c35d-11e7-90b1-7459c9310702.png">
