### ISSUE TITLE
Website: noch nicht gefüllte Navigationspunkte ausgrauen

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#63]
![bildschirmfoto-2017-11-03-um-11 47 46](https://user-images.githubusercontent.com/23217462/32437251-05e8a9ac-c2e7-11e7-8196-770d348eeb2f.jpg)

**Comment by Andreas-Schoenefeldt** [comment]
Navigation möglich machen, wenn man eingeloggt ist?

**Comment by Andreas-Schoenefeldt** [comment]
So, das sollte jetzt gehen - Mit den Menüs in Bachs Welt müssen wir dann nochmal morgen reden, ob wir es bei dem generischen Menü belassen oder das Manuell anlegen.

**Comment by stephan-harmanus** [comment]
<img width="736" alt="bildschirmfoto 2017-11-07 um 20 21 24" src="https://user-images.githubusercontent.com/23217462/32513090-4d0bb3e8-c3f9-11e7-8c92-3b7baba7097c.png">

- Navigationspunkte "Werke" hat noch bei MouseOver einen Underline-Effekt
- Navigationspunkte "Instrumente" und "Orte" sind trotz Deaktivierung noch aktiv und nicht ausgegraut. 
- Navigationspunkt "Personen" ist augegraut und inaktiv, aber hat noch bei MouseOver einen Underline-Effekt.
