### ISSUE TITLE
Favicon für jsbach

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [KplusH/jsbach-timeline#7]
Hallo Stephan,

welches Favicon sollen wir für jsBach verwenden?

Liebe Grüße
Andreas

**Comment by stephan-harmanus** [comment]
![favicon](https://cloud.githubusercontent.com/assets/23217462/20213568/89d9a634-a809-11e6-8066-bf1ed2742621.jpg)
hier für´s Favicon

**Comment by Andreas-Schoenefeldt** [comment]
ok, its uploaded now.
