### ISSUE TITLE
historic maps integration

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [KplusH/jsbach-timeline#73]
info@klokantech.com

- [x] hotspots
- [x] Begrenzung
- [x] callbacks und events
- [ ] hotspot need to be defined dynamically
- [x] Adjust the left navigation to automatically load the first menu point

[konzeption-jsbach-Orte-E2-k.pdf](https://github.com/KplusH/jsbach-timeline/files/1890006/konzeption-jsbach-Orte-E2-k.pdf)

# Configuration
* Create Bachorte Menu
* Create Bachorte DE Pathauto Pattern
* Create Historic Maps Content Type
* Create Bachort Content Type
  * Allow Bachorte Menu

**Comment by Andreas-Schoenefeldt** [comment]
Die Karten funktionieren jetzt wie gewünscht, oder?

**Comment by stephan-harmanus** [comment]
ja, Karten funktionieren.
