### ISSUE TITLE
Orte: Bilder als Gallery oder Slideshow einbinden

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [KplusH/jsbach-timeline#78]
Stephan to discuss, if we can do this via a hard data mask and not as dynamic incontent images.

**Comment by Andreas-Schoenefeldt** [comment]
Easy with the paragraph module :)

**Comment by stephan-harmanus** [comment]
- Kreuz zum Schließen größer machen
- Vor/Zurückbutton in der Galerie
- alternative Bildbeschreibung im vergrößerten Bild am unteren Bildrand auf halbtransparentem Layer einblenden

**Comment by stephan-harmanus** [comment]
Wie kriegen wir in den Griff, dass bei Bildern, die unvorteilhaft in der Vorschau (Thumbnail) beschnitten werden, eine passender Ausschnitt zu sehen ist?

**Comment by stephan-harmanus** [comment]
Dornheim, Bartholomäuskirche. Ich habe als Workaround bis zur Lösung des Probelme eine Vertikale Grafik mit der Bachbüste in Photoshop um weißen Flächen links und rechts erweitert. So paßt es jetzt erst mal ins Seitenformat, ohne dass der Kopf in der Vorschau abgeschnitten ist.

**Comment by stephan-harmanus** [comment]
Vor-zurück button in  Bildergarlerie wird noch benötigt

**Comment by Andreas-Schoenefeldt** [comment]
Die offenen Punkte sind in #84
