### ISSUE TITLE
Glossar & Timeline Entries Brauchen die Standard Tür ins Kalendarium

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [KplusH/jsbach-timeline#8]
* Das icon soll die Tür sein
* Wenn man drauf klickt soll das selbe Detail Fenster wieder aufgehen, das man verlassen hat

**Comment by stephan-harmanus** [comment]
![bildschirmfoto 2016-11-15 um 09 21 38](https://cloud.githubusercontent.com/assets/23217462/20298273/441a973e-ab15-11e6-8cee-e679a629bd32.png)
hier haben wir nun ein Problem. Zwei Werke in einem Timelineeintrag. Hier macht es Sinn, die große Tür unten nicht zu haben und nur kleine Türen direkt hintern den Werken. Die Links führen dann zu Einträgen, die nicht Teil der Timeline sind, aber in einem Glossar Werke erscheinen.
