### ISSUE TITLE
Ladefehler Galerie bei Köthen/Alter Friedhof

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#89]
Wenn man das Zweite Mal eine Galeriebild bei Köthen/alter Friedhof anklickt, läd es nicht mehr
![Bildschirmfoto 2019-03-18 um 12 06 11](https://user-images.githubusercontent.com/23217462/54526521-56efc200-4977-11e9-8017-8c46c991dc10.png)
![Bildschirmfoto 2019-03-18 um 12 07 03](https://user-images.githubusercontent.com/23217462/54526522-56efc200-4977-11e9-9c10-3d995046aeaf.png)

**Comment by stephan-harmanus** [comment]
Bei Arnstadt tritt der Ladefehler auch auf. Bei zweiten Öffen bleiben die Vergrößerungen hängen

<img width="1012" alt="Bildschirmfoto 2019-03-19 um 07 25 16" src="https://user-images.githubusercontent.com/23217462/54584638-362b7900-4a18-11e9-8eee-55101cd2e5c0.png">

**Comment by stephan-harmanus** [comment]
Kann man Vorschaubilder separat vergeben. Wie Du siehst, werden manche Bilder zu willkürlich beschnitten (kopfloser Bach). Ich kann natürlich auch im Nachhinein die Vorschaubilder per Upload angepaßt als Workaround austauschen.
, wie hier im Beispiel, Vorschxaublid rechts
<img width="930" alt="Bildschirmfoto 2019-03-19 um 07 30 24" src="https://user-images.githubusercontent.com/23217462/54584901-f4e79900-4a18-11e9-827c-04c8953b0c3f.png">

**Comment by Andreas-Schoenefeldt** [comment]
Der Ladebug ist behoben - das mit den Vorschaubildern ist leider so nicht möglich, da Drupal nicht zulässt den Schneidepunkt der Bilder zu definieren. 

Man kann es glaube ich für alle auf die Oberkante festlegen, aber die Ergebnisse bleiben auch dann ungewiss.

Liebe Grüße
Andreas

**Comment by stephan-harmanus** [comment]
> Der Ladebug ist behoben - das mit den Vorschaubildern ist leider so nicht möglich, da Drupal nicht zulässt den Schneidepunkt der Bilder zu definieren.
> 
> Man kann es glaube ich für alle auf die Oberkante festlegen, aber die Ergebnisse bleiben auch dann ungewiss.

Bei Festlegung auf die Oberkante wird dann wieder an den Seiten unkalkulierbar was weggeschnitten. Wie oben erwähnt löse ich das am besten über Photoshop, eine Weiße Fläche im korrekten Vorschauformat, in die ich das entsprechende Bild einlege.
