### ISSUE TITLE
Timeline Debugging

### ISSUE THREAD

**Issue by stephan-harmanus** [KplusH/jsbach-timeline#9]
Feld für Taufe und Geburt ist zu kurz, da die Datumlänge mit einbezogen werden muß

**Comment by Andreas-Schoenefeldt** [comment]
This is connected to #39, because this field will need to be as well included.

**Comment by stephan-harmanus** [comment]
![bildschirmfoto 2016-12-07 um 16 51 14](https://cloud.githubusercontent.com/assets/23217462/20974839/c7effd4e-bc9d-11e6-8702-6fda9dc39d4f.png)
![bildschirmfoto 2016-12-07 um 16 51 20](https://cloud.githubusercontent.com/assets/23217462/20974840/c7f67746-bc9d-11e6-8b4b-48d161a53607.png)
![bildschirmfoto 2016-12-07 um 16 51 27](https://cloud.githubusercontent.com/assets/23217462/20974841/c7f69e9c-bc9d-11e6-9803-a128002640e9.png)

Zeitgeschehen: Ereignisse werden oben abgeschnitten, sind außerhalb des Sichtbereichs

**Comment by stephan-harmanus** [comment]
![bildschirmfoto 2016-12-08 um 08 13 06](https://cloud.githubusercontent.com/assets/23217462/21001012/466eb59a-bd1e-11e6-800e-f6cb166fe6c5.png)

Wenn man von hier auf den Link "Johannes-Passion BWV 245" klickt, wird auf der Website nicht die Navigation angezeigt.

**Comment by Andreas-Schoenefeldt** [comment]
Done :)
